# Generated by Django 4.2.29 on 2026-04-04 18:53

from django.db import migrations, models


SLUG_TO_IMAGE = {
    "luxury-buyers-checklist-2026": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
    "staging-that-sells-high-end-homes": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    "interest-rates-and-luxury-market": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    "investing-in-vacation-rentals": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    "choosing-the-right-neighborhood": "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=80",
    "selling-your-home-winter-guide": "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=1200&q=80",
    "new-construction-vs-resale": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
    "eco-friendly-upgrades-value": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
    "global-buyers-us-luxury-real-estate": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    "preparing-for-the-home-inspection": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
    "condo-vs-coop-urban-buying": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
    "multiple-offers-winning-strategy": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80",
    "downsizing-after-empty-nest": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
    "waterfront-home-essentials": "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&q=80",
    "historic-home-renovations-permits": "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&q=80",
    "hoa-red-flags-buyers": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
    "pricing-your-home-to-move": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
    "1031-exchange-basics-investors": "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1200&q=80",
    "smart-home-tech-and-resale": "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80",
    "moving-with-pets-smooth-transition": "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200&q=80",
}


def set_featured_image_urls(apps, schema_editor):
    BlogPost = apps.get_model("website", "BlogPost")
    for slug, url in SLUG_TO_IMAGE.items():
        BlogPost.objects.filter(slug=slug).update(featured_image_url=url)


def clear_featured_image_urls(apps, schema_editor):
    BlogPost = apps.get_model("website", "BlogPost")
    BlogPost.objects.filter(slug__in=list(SLUG_TO_IMAGE.keys())).update(featured_image_url="")


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_seed_more_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Optional image URL (e.g. CDN). Shown when no file is uploaded above.', max_length=500),
        ),
        migrations.RunPython(set_featured_image_urls, clear_featured_image_urls),
    ]
