# Generated by Django 4.2.29 on 2026-04-04 19:00

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blog_richtext_slug_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
