# Generated by Django 4.2.29 on 2026-04-04 21:25

from django.db import migrations, models


def seed_properties(apps, schema_editor):
    Property = apps.get_model("website", "Property")
    from website import properties_data

    for i, row in enumerate(properties_data._RAW_PROPERTIES):
        Property.objects.update_or_create(
            slug=row["slug"],
            defaults={
                "name": row["name"],
                "location": row["location"],
                "price_display": row["price_display"],
                "rating": row["rating"],
                "status": row["status"],
                "brochure_url": row.get("brochure_url") or "",
                "description": row["description"],
                "developer_name": row["developer_name"],
                "about_developer": row["about_developer"],
                "rera_id": row["rera_id"],
                "project_size": row["project_size"],
                "map_embed_url": row["map_embed_url"],
                "images": row["images"],
                "amenities": row["amenities"],
                "videos": row["videos"],
                "faq": row["faq"],
                "is_published": True,
                "sort_order": i,
            },
        )


def unseed_properties(apps, schema_editor):
    Property = apps.get_model("website", "Property")
    from website import properties_data

    Property.objects.filter(slug__in=[r["slug"] for r in properties_data._RAW_PROPERTIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_fix_smart_home_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=240)),
                ('price_display', models.CharField(help_text='Shown on cards, e.g. "$1.25M — from"', max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('status', models.CharField(choices=[('Ready to move', 'Ready to move'), ('Under construction', 'Under construction'), ('New launch', 'New launch')], default='Ready to move', max_length=40)),
                ('brochure_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('developer_name', models.CharField(max_length=200)),
                ('about_developer', models.TextField()),
                ('rera_id', models.CharField(max_length=120, verbose_name='RERA ID')),
                ('project_size', models.CharField(help_text='E.g. acres, towers, unit count', max_length=200)),
                ('map_embed_url', models.URLField(max_length=800, verbose_name='Map embed URL')),
                ('images', models.JSONField(default=list, help_text='Up to 10 image URLs as JSON list, e.g. ["https://...", "..."]')),
                ('amenities', models.JSONField(default=list, help_text='List of strings, e.g. ["Pool", "Gym"]')),
                ('videos', models.JSONField(default=list, help_text='Up to 2 objects: [{"title":"…","embed_url":"https://youtube.com/embed/…"}, …]')),
                ('faq', models.JSONField(default=list, help_text='List of objects: [{"q":"…","a":"…"}, …]')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the properties page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_properties, unseed_properties),
    ]
