# Generated by Django 4.2.29 on 2026-04-04 21:32

from django.db import migrations, models
from django.utils.text import slugify
import django.db.models.deletion


def seed_cities(apps, schema_editor):
    City = apps.get_model("website", "City")
    from website.location_constants import INDIAN_CITY_LOCATIONS

    for i, name in enumerate(sorted(INDIAN_CITY_LOCATIONS)):
        slug = (slugify(name) or f"city-{i}")[:140]
        candidate = slug
        n = 1
        while City.objects.filter(slug=candidate).exists():
            suffix = f"-{n}"
            candidate = f"{slug[: 140 - len(suffix)]}{suffix}"
            n += 1
        City.objects.get_or_create(
            name=name,
            defaults={"sort_order": i, "slug": candidate},
        )


def unseed_cities(apps, schema_editor):
    City = apps.get_model("website", "City")
    from website.location_constants import INDIAN_CITY_LOCATIONS

    City.objects.filter(name__in=list(INDIAN_CITY_LOCATIONS)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in admin and on filters (lower first).')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Address or area line shown on cards and detail (e.g. neighbourhood, full address).', max_length=240),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, help_text='When set, the project is grouped under this city in property filters (only cities with listings appear on the site).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='website.city'),
        ),
        migrations.RunPython(seed_cities, unseed_cities),
    ]
