# Generated by Django 4.2.29 on 2026-04-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='project_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('sco', 'SCO')], db_index=True, default='residential', max_length=20, verbose_name='Project type'),
        ),
    ]
