# Generated by Django 4.2.29 on 2026-04-05

from django.db import migrations


def resync_properties_from_seed(apps, schema_editor):
    Property = apps.get_model("website", "Property")
    City = apps.get_model("website", "City")
    from website import properties_data

    for i, row in enumerate(properties_data._RAW_PROPERTIES):
        defaults = {
            "name": row["name"],
            "location": row["location"],
            "price_display": row["price_display"],
            "rating": row["rating"],
            "status": row["status"],
            "brochure_url": row.get("brochure_url") or "",
            "description": row["description"],
            "developer_name": row["developer_name"],
            "about_developer": row["about_developer"],
            "rera_id": row["rera_id"],
            "project_size": row["project_size"],
            "map_embed_url": row["map_embed_url"],
            "images": row["images"],
            "amenities": row["amenities"],
            "videos": row["videos"],
            "faq": row["faq"],
            "is_published": True,
            "sort_order": i,
        }
        project_type = row.get("project_type")
        if project_type:
            defaults["project_type"] = project_type
        city_name = row.get("city_name")
        if city_name:
            city = City.objects.filter(name=city_name).first()
            if city:
                defaults["city_id"] = city.id
        Property.objects.update_or_create(slug=row["slug"], defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_property_project_type"),
    ]

    operations = [
        migrations.RunPython(resync_properties_from_seed, migrations.RunPython.noop),
    ]
