# Generated by Django 4.2.29 on 2026-04-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_sync_property_images_from_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('callback', 'Property callback'), ('contact', 'Contact us')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('property', models.ForeignKey(blank=True, help_text='Set when the visitor requested a callback from a property page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_enquiries', to='website.property')),
            ],
            options={
                'verbose_name': 'Site enquiry',
                'verbose_name_plural': 'Site enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
