# Generated by Django 4.2.29 on 2026-04-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_site_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='Organization or publication that granted the recognition.', max_length=200)),
                ('year_label', models.CharField(blank=True, help_text='E.g. "2024" or "2023–2025".', max_length=40, verbose_name='Year / period')),
                ('summary', models.TextField(blank=True, help_text='Short description on the awards page.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL when no file is uploaded.', max_length=500)),
                ('link_url', models.URLField(blank=True, help_text='Optional link (press release, certificate, etc.).', max_length=500, verbose_name='External link')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this item from the website.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Award / recognition',
                'verbose_name_plural': 'Awards & recognitions',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
