# Generated by Django 4.2.29 on 2026-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_seed_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEventsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('news', 'News & updates'), ('events', 'Events highlights')], db_index=True, default='news', help_text='Which block on the News & updates page this item appears in.', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Optional caption; not shown on the image grid (for admin / future use).')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news-events/')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL when no file is uploaded.', max_length=500)),
                ('link_url', models.URLField(blank=True, help_text='Optional related article or event page.', max_length=500, verbose_name='External link')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this item from the website.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within its section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News / event highlight',
                'verbose_name_plural': 'News & events gallery',
                'ordering': ['section', 'sort_order', '-created_at'],
            },
        ),
    ]
